apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snowflake2
  name: snowflake2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snowflake2
  template:
    metadata:
      labels:
        app: snowflake2
    spec:
      containers:
      - image: registry.k8s.io/serve_hostname
        imagePullPolicy: Always
        name: snowflake
