apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trolley-agent-service-account
subjects:
- kind: ServiceAccount
  name: trolley-agent-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: trolley-agent
  apiGroup: rbac.authorization.k8s.io