apiVersion: apps/v1
kind: Deployment
metadata:
  name: trolley-agent-deployment
  labels:
    app: trolley-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trolley-agent
  template:
    metadata:
      labels:
        app: trolley-agent
    spec:
      containers:
      - name: trolley-agent
        volumeMounts:
          - mountPath: /etc/kubernetes
            name: kubernetes
        image: pavelzagalsky/trolley_agent:latest
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: INTERNAL_CLUSTER_MODE
          value: "true"
        - name: CLUSTER_NAME
          value: "shuki"
        - name: CONTEXT_NAME
          value: ""
        - name: CLUSTER_TYPE
          value: "gke"
        - name: FETCH_INTERVAL
          value: "5"
        - name: MONGO_USER
          value: "pavel"
        - name: MONGO_PASSWORD
          value: "Pp59aa!!"
        - name: MONGO_URL
          value: "34.123.171.234"
        - name: PROJECT_NAME
          value: "trolley"
        - name: KUBECONFIG
          value: /etc/kubernetes/admin.conf
      serviceAccountName: trolley-agent-service-account
      volumes:
        - emptyDir: { }
          name: kubernetes