name: AKS Deletion
on:
  repository_dispatch:
    types: aks-delete-api-trigger

jobs:
  testing_actions:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Echo the values
        run: |
          echo "${{ github.event.client_payload.cluster_name }}"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deleting Cluster
        if: always()
        run: |
          az aks delete --name=${{ github.event.client_payload.cluster_name }} --resource-group=MyResourceGroup --yes