name: EKS Caching
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  gke_caching:
    runs-on: ubuntu-20.04
    steps:
      - uses: 'actions/checkout@v3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Caching Tasks
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r requirements.txt
          python3 web/scripts/eks_caching_script.py
