name: EKS Deployment
on:
  repository_dispatch:
    types: eks-build-api-trigger

jobs:
  testing_actions:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: test env
        run: echo
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Generate UUID
        run: |
          uuidgen > uuid
          ls -la
          pwd
          echo "uuid=$(cat uuid)" >> $GITHUB_ENV
      - name: Echo the values
        run: |
          echo "${{ env.uuid }}"
          echo "${{ github.event.client_payload.region_name }}"
          echo "${{ github.event.client_payload.cluster_name }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Trigger EKS Build
        run: |
          aws eks create-cluster --region ${{ github.event.client_payload.region_name }} --name ${{ github.event.client_payload.cluster_name }} --kubernetes-version ${{ github.event.client_payload.cluster_version }} --role-arn arn:aws:iam::553159257253:role/pavel-eks-1 --resources-vpc-config subnetIds=${{ github.event.client_payload.subnets }}