name: EKS Deployment
on:
  repository_dispatch:
    types: eks-build-api-trigger

jobs:
  testing_actions:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: test env
        run: echo
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Generate UUID
        run: |
          uuidgen > uuid
          ls -la
          pwd
          echo "uuid=$(cat uuid)" >> $GITHUB_ENV
      - name: Echo the values
        run: |
          echo "${{ env.uuid }}"
          echo "${{ github.event.client_payload.region_name }}"
          echo "${{ github.event.client_payload.cluster_name }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update kube config
        run: |
          aws eks --region ${{ github.event.client_payload.region_name }} update-kubeconfig --name  ${{ github.event.client_payload.cluster_name }}
          cat /home/runner/.kube/config
#          gcloud beta container --quiet --project boneseye clusters create ${{ github.event.client_payload.cluster_name }} --zone ${{ github.event.client_payload.zone_name }} --no-enable-basic-auth --cluster-version ${{ github.event.client_payload.cluster_version }} --release-channel stable --machine-type e2-medium --image-type COS --disk-type pd-standard --disk-size 100 --metadata disable-legacy-endpoints=true --scopes https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --max-pods-per-node 110 --num-nodes ${{ github.event.client_payload.num_nodes }} --logging=SYSTEM,WORKLOAD --monitoring=SYSTEM --enable-ip-alias --network projects/boneseye/global/networks/default --subnetwork projects/boneseye/regions/${{ github.event.client_payload.region_name }}/subnetworks/default --no-enable-intra-node-visibility --default-max-pods-per-node 110 --no-enable-master-authorized-networks --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver --enable-autoupgrade --enable-autorepair --max-surge-upgrade 1 --max-unavailable-upgrade 0 --enable-shielded-nodes --node-locations ${{  github.event.client_payload.zone_name }}


#--project "boneseye" clusters create $CLUSTER_NAME --zone $ZONE_NAME --no-enable-basic-auth --cluster-version $CLUSTER_VERSION --release-channel "stable" --machine-type "e2-medium" --image-type $IMAGE_TYPE --disk-type "pd-standard" --disk-size "100" --metadata disable-legacy-endpoints=true --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --max-pods-per-node "110" --num-nodes $NUM_NODES --logging=SYSTEM,WORKLOAD --monitoring=SYSTEM --enable-ip-alias --network "projects/boneseye/global/networks/default" --subnetwork "projects/boneseye/regions/$REGION_NAME/subnetworks/default" --no-enable-intra-node-visibility --default-max-pods-per-node "110" --no-enable-master-authorized-networks --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver --enable-autoupgrade --enable-autorepair --max-surge-upgrade 1 --max-unavailable-upgrade 0 --enable-shielded-nodes --node-locations $ZONE_NAME
#curl -H "Accept: application/vnd.github.everest-preview+json" \
#    -H "Authorization: token <token>" \
#    --request POST \
#    --data '{"event_type": "gke-build-api-trigger", "client_payload": { "cluster_name": "pavel-cluster-test","cluster_version": "1.22.8-gke.201","zone_name": "asia-east1-b","region_name": "asia-east1", "num_nodes": 2}}' \
#    https://api.github.com/repos/LiorYardeni/trolley/dispatches