name: GKE Caching
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
#    - cron: '* * * * *'

jobs:
  gke-caching:
    runs-on: ubuntu-20.04
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDS_JSON }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: gcloud info
      - name: Installing GKE Cluster
        run: |
          export KUBECONFIG=/tmp/kubeconfig
          gcloud container images list
          gcloud components install beta --quiet
          gcloud beta container --quiet --project boneseye clusters create ${{ github.event.client_payload.cluster_name }} --zone ${{ github.event.client_payload.zone_name }} --no-enable-basic-auth --cluster-version ${{ github.event.client_payload.cluster_version }} --release-channel stable --machine-type e2-medium --image-type ${{ github.event.client_payload.image_type }} --disk-type pd-standard --disk-size 100 --metadata disable-legacy-endpoints=true --scopes https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --max-pods-per-node 110 --num-nodes ${{ github.event.client_payload.num_nodes }} --logging=SYSTEM,WORKLOAD --monitoring=SYSTEM --enable-ip-alias --network projects/boneseye/global/networks/default --subnetwork projects/boneseye/regions/${{ github.event.client_payload.region_name }}/subnetworks/default --no-enable-intra-node-visibility --default-max-pods-per-node 110 --no-enable-master-authorized-networks --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver --enable-autoupgrade --enable-autorepair --max-surge-upgrade 1 --max-unavailable-upgrade 0 --enable-shielded-nodes --node-locations ${{  github.event.client_payload.zone_name }}
          gcloud container clusters get-credentials ${{ github.event.client_payload.cluster_name }} --region ${{ github.event.client_payload.zone_name }} --project boneseye
          cat /tmp/kubeconfig
          
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Post Deployment Tasks
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r requirements.txt
          python3 web/scripts/gke_caching_script.py
