name: GKE Deployment
on:
  workflow_dispatch:

jobs:
  testing_actions:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: test env
        run: echo
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Generate UUID
        run: |
          uuidgen > uuid
          ls -la
          pwd
          echo "uuid=$(cat uuid)" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.uuid }}"

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDS_JSON }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: gcloud info
      - name: Checking gcloud
        run: |-
          gcloud container images list
          gcloud components install beta --quiet
          gcloud beta container --quiet --project boneseye clusters create pavel-gke-nnuqd --zone asia-east1-b --no-enable-basic-auth --cluster-version 1.22.8-gke.201 --release-channel stable --machine-type e2-medium --image-type COS --disk-type pd-standard --disk-size 100 --metadata disable-legacy-endpoints=true --scopes https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --max-pods-per-node 110 --num-nodes 2 --logging=SYSTEM,WORKLOAD --monitoring=SYSTEM --enable-ip-alias --network projects/boneseye/global/networks/default --subnetwork projects/boneseye/regions/asia-east1/subnetworks/default --no-enable-intra-node-visibility --default-max-pods-per-node 110 --no-enable-master-authorized-networks --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver --enable-autoupgrade --enable-autorepair --max-surge-upgrade 1 --max-unavailable-upgrade 0 --enable-shielded-nodes --node-locations asia-east1-b 
