name: Expired Clusters Deletion2
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Post Deployment Tasks
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r requirements.txt
          python3 web/scripts/gke_caching_script.py --cluster_type gke