apiVersion: apps/v1
kind: Deployment
metadata:
  name: trolley-deployment
  labels:
    app: trolley
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trolley
  template:
    metadata:
      labels:
        app: trolley
    spec:
      containers:
      - name: trolley- server
        image: pavelzagalsky/trolley:latest
        ports:
        - containerPort: 8081
        env:
         - name SECRET_KEY
           value "something"
         - name MONGO_USER
           value "something"
         - name MONGO_PASSWORD
           value "something"
         - name MONGO_URL
           value "something"
         - name ACTION_TOKEN
           value "something"
         - name PROJECT_NAME
           value "trolley"